train:
  model: DeepLabV3Plus
  max_epoch: 8
  lr: 0.0001
  smooth_factor: 0.1
  dir_suffix: f3_st
valid:
  metric: Mean IoU
dataset:
  name: f3_st
  pseudo_label_path: /volume/CONSS_114/runs/f3_sup_DeepLabV3Plus/best_model_prediction_f3.npz
  train_labels_path: /volume/dataset/f3/train/train_labels.npy
  test1_labels_path: /volume/dataset/f3/test_once/test1_labels.npy
  test2_labels_path: /volume/dataset/f3/test_once/test2_labels.npy
  train_data_path: /volume/dataset/f3/train/train_seismic.npy
  test1_data_path: /volume/dataset/f3/test_once/test1_seismic.npy
  test2_data_path: /volume/dataset/f3/test_once/test2_seismic.npy
  slice_width: 256
  batch_size: 2
  sample_position: [0,100,200,300,400,500,600]
