train:
  max_epoch: 8
  classes: 6
  lr: 0.001
  bn_eps: 0.00001
  bn_momentum: 0.1
  smooth_factor: 0.1
  dir_suffix: seam_cps_DeepLabV3Plus
valid:
  metric: Mean IoU
dataset:
  name: seam_semi
  train_data_path: /volume/dataset/seam_ai/data_train.npz
  train_labels_path: /volume/dataset/seam_ai/labels_train.npz
  slice_width: 256
  batch_size: 2
  sample_position: [0,100,200,300,400,500,589]